# Generated by Django 3.2.12 on 2023-12-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.coach')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.position')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.position'),
        ),
    ]
